var aa = 100;
var a = 95;
var bb = 85
var b = 80;
var cc = 75;
var c = 65;
var dd = 60;
var d = 55;

var testResult = 100;

if (testResult === aa) {
    console.log("You got an A+ ");
} else if  (testResult === a) {
    console.log("You got an A");
} else if (testResult === bb) {
    console.log(" You got a B+ ");
} else if (testResult === b) {
    console.log(" You got a B");
} else if (testResult === cc) {
    console.log("You got a C+ ");
} else if (testResult === c) {
    console.log(" You got a C");
} else if (testResult === dd) {
    console.log("You got a D+ ");
} else if (testResult === d) {
    console.log("You got a D");
} else { console.log("You got an F");
}
